CREATE TABLE log_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    duration BIGINT NOT NULL,
    type VARCHAR(100),
    host VARCHAR(100),
    alert BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (event_id)
);